### PR TITLE
Add `applyLeibniz` and variants

### PR DESCRIPTION
**Pull request by rgrempel**
Building on the discussion in #9, this adds `applyLeibniz` and variously-kinded variants.

The `applyLeibniz` functions are essentially analogous to `liftLeibniz`, except that you provide two parameters. The first parameter proves the equality of the type constructors. The second parameter proves the equality of one of the type arguments. So, you lift the "distinct but equal" type arguments into distinct but equal type constructors (rather than requiring that the type constructors match up-front).

In terms of the [Haskell GADT type equality library](https://hackage.haskell.org/package/base-4.10.1.0/docs/Data-Type-Equality.html), this represents a combination of `outer` and `apply`, which are there defined as:

```haskell
apply :: (f :~: g) -> (a :~: b) -> f a :~: g b
outer :: (f a :~: g b) -> f :~: g
```

Unless I'm missing something, those definitions only make sense if you have polykinds. Basically, `apply` lets you do type application (whatever the kinds), and `outer` supplies the needed evidence about the type constructors (again, whatever the kinds).

In the absence of polykinds, I think we need to combine `apply` and `outer` in something I've proposed we call `applyLeibniz`.

Note that `liftLeibniz` and variants are now implemented in terms of `applyLeibniz` and variants, because the `liftLeibniz` signatures allow us to provide trivial evidence of the equality of the type constructors. 

So, `applyLeibniz` requires two parameters: 

- evidence that the type constructors are equal
- evidence that the type arguments are equal

```purs
applyLeibniz :: forall f g a b c d. f c ~ g d -> a ~ b -> f a ~ g b
applyLeibniz _ _ = Leibniz unsafeCoerce
```

Whereas `liftLeibniz` only requires one parameter (as previously) ... since the type constructors necessarily match, we can use `identity` to supply the additional parameter.

```purs
liftLeibniz :: forall f a b. a ~ b -> f a ~ f b
liftLeibniz = applyLeibniz identity
```

It occurred to me to simply modify `liftLeibniz` to take the extra parameter, and document the breaking change (i.e. people would now have to say `liftLeibniz identity` where before they just said `liftLeibniz`). However, the signatures for some of the variants get a bit hairy ... e.g.

```purs
applyLeibniz3of3 :: forall f g f1 f2 f3 g1 g2 g3 a b c d. f f1 f2 f3 ~ g g1 g2 g3 -> a ~ b -> f c d a ~ g c d b
applyLeibniz3of3 _ _ = Leibniz unsafeCoerce
```

Given that many type variables, it seemed to me that retaining the current, simpler signature for `liftLeibniz3of3` had some value.

Note that it is because there are so many type variables that I started numbeing them -- I think it's easier to follow the logic that way, rather than using more letters.

So, I think this is the best we can do without polykinds, unless there's something I haven't thought of.

### CODE REVIEW

**Comment by rgrempel** [comment]
BTW, would it be crazy to have some syntax to allow `_` to be used as a type variable, in cases where you don't care what the type variable is because it doesn't match anything? If we had that, then the signature for `applyLeibniz3of3` could be something like:

```purs
applyLeibniz3of3 :: forall f g a b c d. f _ _ _ ~ g _ _ _ -> a ~ b -> f c d a ~ g c d b
```

Actually, now that I try it, we **do** have that ... it's a type wildcard, of course, and it actually sort of works -- at the cost of the warnings (i.e. it reports an inferred type we don't really care about).

**Comment by rgrempel** [comment]
Just to expand on the last comment, if we replaced all the `f f1 f2 ~ g g1 g2` with `f _ _ ~ g _ _` then it appears to work fine, but you do get a bunch of warnings of this form

```
[14/14 WildcardInferredType] src/Data/Leibniz.purs:111:57

  111  applyLeibniz2of3 :: forall f g a b c d. f _ _ _ ~ g _ _ _ -> a ~ b -> f c a d ~ g c b d
                                                               ^

  Wildcard type definition has the inferred type

    t0

  in value declaration applyLeibniz2of3

  where t0 is an unknown type
```

And, I'm assuming that to always generate these warnings would be undesirable, even though the types would read very nicely that way.

**Comment by paf31** [comment]
👍 Thanks! Again, could you please rebase?

**Comment by paf31** [comment]
I would prefer not to use wildcards for now, even though they do tidy  the signatures up quite a bit.

**Comment by rgrempel** [comment]
Super, I have rebased against master.

**Comment by paf31** [comment]
Thanks again!

**Pull request merged**
